services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
      args:
        - POSTGRES_VERSION=17
      target: release
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
      args:
        - NODE_VERSION=22
      target: release
    ports:
      - "3000:3000"
