# Generated by Django 5.1.5 on 2025-02-19 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tko', '0002_article_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
