# Generated by Django 5.1.5 on 2025-03-12 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tko', '0005_alter_article_date_articlepage'),
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('color', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='active_to',
        ),
        migrations.AlterField(
            model_name='articlepage',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.RemoveField(
            model_name='articlepage',
            name='image',
        ),
        migrations.AddField(
            model_name='articlepage',
            name='image',
            field=models.ManyToManyField(to='wagtailimages.image'),
        ),
    ]
