# Generated by Django 5.1.5 on 2025-03-10 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tko', '0005_remove_article_image_alter_article_date_articleimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleimage',
            name='is_main',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.FileField(blank=True, default='default.png', upload_to='images/%Y'),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.FileField(upload_to='images/%Y'),
        ),
    ]
