# Generated by Django 5.1.5 on 2025-03-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tko', '0006_remove_articleimage_is_main_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='articleimage',
            name='image',
            field=models.FileField(default='default.png', upload_to='images/%Y'),
        ),
    ]
